language: node_js
sudo: false
node_js:
 - "4.0"

before_script:
 - npm install
 - gem install sass
 - ./node_modules/.bin/grunt build

script:
 - karma start karma.conf.js

before_install:
  - npm install -g karma-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
 - ./node_modules/.bin/grunt remapIstanbul
 - ./node_modules/.bin/coveralls < .coverage/lcov.info

