language: node_js
sudo: false
node_js:
 - "4.0"
addons:
  firefox: "39.0"

before_script:
 - npm install
 - gem install sass
 - ./node_modules/.bin/grunt build

script:
 - karma start karma.conf.js

before_install:
  - npm install -g karma-cli

after_script:
 - ./node_modules/.bin/grunt remapIstanbul
 - ./node_modules/.bin/coveralls < .coverage/lcov.info

